swagger: "2.0"
info:
  description: Forex-Python API
  version: 1.0.0
  title: CurrencyConverter
host: virtserver.swaggerhub.com
basePath: /Dkazem91/KintoHubCurrencies/1
schemes:
- https
paths:

  /available_currencies:
    get:
      summary: Get an array of available currencies
      description: Gets an array of the three letter ISO 4217 alphabetic codes
      operationId: currencies_get
      produces:
      - application/json
      responses:
        200:
          description: An array of the 3 letter ISO 4217 alphabetic codes for all available currencies.
          schema:
            $ref: "#/definitions/ISO4217s"
      x-swagger-router-controller: swagger_server.controllers.default_controller

  /get_rates/{from}:
    get:
      summary: Get all rates against a currency.
      description: Gets rates of all available currencies based on base currency (from parameter).
      operationId: get_rates_get
      produces:
      - application/json
      parameters:
      - name: date
        in: query
        description: YYYY-MM-DD format of date to check rates on.
        required: false
        type: string
        default: current date
      - name: from
        in: path
        description: Base currency to get rates against.
        required: true
        type: string
      responses:
        200:
          description: Array of Conversion of all available currencies against the base currency.
          schema:
            $ref: "#/definitions/Conversions"
      x-swagger-router-controller: swagger_server.controllers.default_controller

  /get_rate/{from}/{to}:
    get:
      summary: Gets rate from one currency to another.
      description: Returns a Conversion with from_amt always equal to 1.
      operationId: get_rate_get
      produces:
      - application/json
      parameters:
      - name: date
        in: query
        description: YYYY-MM-DD format of date to check rates on
        required: false
        type: string
        default: current date
      - name: from
        in: path
        description: Three letter ISO 4217 alphabetic code for the currency that's being converted from.
        required: true
        type: string
      - name: to
        in: path
        description: Three letter ISO 4217 alphabetic code for the currency that's being converted to.
        required: true
        type: string
      responses:
        200:
          description: A Conversion object with from_amt equal to 1.
          schema:
            $ref: "#/definitions/Conversion"
      x-swagger-router-controller: swagger_server.controllers.default_controller

  /convert/{from}/{to}/{amt}:
    get:
      summary: gives converted amount based on parameters
      description: returns an amount, query, and info
      operationId: convert_get
      produces:
      - application/json
      parameters:
      - name: date
        in: query
        description: YYYY-MM-DD format of date to check rates on
        required: false
        type: string
        default: current date
      - name: from
        in: path
        description: Three letter ISO 4217 alphabetic code for the currency that's being converted from.
        required: true
        type: string
      - name: to
        in: path
        description: Three letter ISO 4217 alphabetic code for the currency that's being converted to.
        required: true
        type: string
      - name: amt
        in: path
        description: The amount of base currency to convert from.
        required: true
        type: number            # can't be integer since users need to be able to use decimals
      responses:
        200:
          description: Conversion object based on parameters
          schema:
            $ref: "#/definitions/Conversion"
      x-swagger-router-controller: swagger_server.controllers.default_controller

definitions:
  # Array of 3 letter ISO 4217 alphabetic codes.
  ISO4217s:
    type: array
    items:
      type: string
      description: Three letter ISO 4217 alphabetic code

  # Describes the conversion from one currency to another.
  Conversion:
    type: object
    properties:
      date:
        type: string
        description: YYYY-MM-DD format of date the conversion data is based off of
      from_iso:
        type: string
        description: Three letter ISO 4217 alphabetic code for the currency that's being converted from
      to_iso:
        type: string
        description: Three letter ISO 4217 alphabetic code for the currency that's being converted to
      from_amt:
        type: number
        description: the amount of from_iso being converted
      to_amt:
        type: number
        description: the amount of to_iso that the amount of from_iso converts to
    required:
      - date
      - from_iso
      - to_iso
      - from_amt
      - to_amt

  # Array of Conversions
  Conversions:
    type: array
    items:
      $ref: "#/definitions/Conversion"
