# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.conversion import Conversion  # noqa: F401,E501
from swagger_server import util


class Conversions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, list_of_conversions: List[Conversion]=None):  # noqa: E501
        """Conversions - a model defined in Swagger

        :param list_of_conversions: The list_of_conversions of this Conversions.  # noqa: E501
        :type list_of_conversions: List[Conversion]
        """
        self.swagger_types = {
            'list_of_conversions': List[Conversion]
        }

        self.attribute_map = {
            'list_of_conversions': 'list_of_conversions'
        }

        self._list_of_conversions = list_of_conversions

    @classmethod
    def from_dict(cls, dikt) -> 'Conversions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Conversions of this Conversions.  # noqa: E501
        :rtype: Conversions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_of_conversions(self) -> List[Conversion]:
        """Gets the list_of_conversions of this Conversions.


        :return: The list_of_conversions of this Conversions.
        :rtype: List[Conversion]
        """
        return self._list_of_conversions

    @list_of_conversions.setter
    def list_of_conversions(self, list_of_conversions: List[Conversion]):
        """Sets the list_of_conversions of this Conversions.


        :param list_of_conversions: The list_of_conversions of this Conversions.
        :type list_of_conversions: List[Conversion]
        """
        if list_of_conversions is None:
            raise ValueError("Invalid value for `list_of_conversions`, must not be `None`")  # noqa: E501

        self._list_of_conversions = list_of_conversions
